### PR TITLE
[WIP] Fix for #85

### PR DESCRIPTION
**Pull request by grapereader**
This is not ready to merge.

To keep #85 clean, I will keep implementation-specific comments within this PR until it is ready & tested.

### CODE REVIEW

**Comment by grapereader** [comment]
Comment moved from original issue:

---

Well, with some debugging I was able to trace the exception in my OP to divide by zero errors caused by the minetest dummy textures being 1x1 pixels.

Clamping these values to 1, I was able to push the client through the login process:
image

Which reveals that somehow I have totally borked all texture sending :) not even basic textures are loading properly.
image

Clearly I'm doing something totally wrong... though added logging to multiserver indicates I am sending the textures. 🤷‍♂️ Strange indeed.

**Comment by HimbeerserverDE** [comment]
I found two problems with your code:
1. Media is announced during client initialisation, thus SafeServerName will always return the name of the default server
2. The count of media files (`len(media[currentSrvname])`, media.go:294) is not equal to the amount of files that are actually being announced (`len(GetAllNames(currentSrvname))`, media.go:295), this is probably the cause of the client crash

**Comment by grapereader** [comment]
> The count of media files (len(media[currentSrvname]), media.go:294) is not equal to the amount of files that are actually being announced (len(GetAllNames(currentSrvname)), media.go:295), this is probably the cause of the client crash

Yes! That was it. I no longer crash.

I have tried to get the PUSH to work but it is as you said: Minetest does not update the textures in-game with new media...

Reading the Minetest source now to figure out why this is going on. Maybe if it is a bug I can fix it... Though the option of prefixing all textures with the servername could be a backwards-compatible solution.

**Comment by grapereader** [comment]
Yeah no success on the push. It seems to be a longstanding issue: https://forum.minetest.net/viewtopic.php?t=21932
> the inability to push new media to the client on the fly

I have started down the path to approach 2: give each media item a unique name from the outset. This will require deep packet inspection of the NodeDefs... The []byte forming the bulk of this packet body is a serialized NodeDefManager, containing some # of serialized ContentFeatures, each of which contains serialized TileDefs containing references to the media by name.
image

image

image

It is nested 3 levels of serialization deep. Still. I think we should be able to wrap the []byte in a Reader, and skip until we get to the parts that need modifying, writing out to a Writer as we go? Something like that...

**Comment by HimbeerserverDE** [comment]
Yeah, minetest networking can really be a pain sometimes. I think skipping the irrelevant parts this way is a good idea.

**Comment by HimbeerserverDE** [comment]
Are you still working on this?

**Comment by grapereader** [comment]
Not really.

**Comment by HimbeerserverDE** [comment]
Fixed in the successor project, see https://github.com/HimbeerserverDE/multiserver/issues/85#issuecomment-1817860579 for details.

**Pull request closed without merging**
